version: '3.9'
services:
  web:
    env_file:
      - .env
    build: .
    command: npm run dev
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - mongodb
      - postgres

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 7017:27017

  postgres:
    env_file:
      - .env
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mongo_data: {}
  redis:
  postgres:
