version: '3.9'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - DB_HOST=mongodb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - 7017:27017

volumes:
  mongo_data: {}
