version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:14.20.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: set variables
          command: |
            touch .env
            echo "NODE_ENV=$NODE_ENV" >> .env
            echo "MONGODB_URL=$MONGODB_URL" >> .env
            echo "ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET" >> .env
      - run:
          name: run api test
          command: npm test
      - store_artifacts:
          path: ~/repo/api